### ISSUE TITLE
Bug: Ship doesn't auto select.

### ISSUE THREAD

**Issue by harpiesd96** [mjrmyke/Asteroids#9]
Whenever the User presses Start game, the ship does not get selected automatically (it may actually get selected for one frame, i pressed alt f s and kept holding s and the ship moved down... somehow. and i could not select it again.)

**Comment by mjrmyke** [comment]
Still working on this, any solutions would be appreciated. Apparently, if setfocus is called before the item is drawn to screen, it does nothing. We are calling setfocus on the ship at the end of mainwindow.cpp, which should work. 

I am having trouble finding 
A) what has focus instead of the ship
B) why the ship doesn't have focus.

**Comment by harpiesd96** [comment]
Bug is now fixed. I just made it so that there is only one window, and it changes scenes.
